

const traduccionesPortal = {
  es: {
    "abrir_menu_de_cuenta": "Abrir menu de cuenta",
    "abrir_cuenta": "Abrir cuenta",
    "configuracion": "Configuracion",
    "abrir_menu_de_navegacion": "Abrir menu de navegacion",
    "perfil_y_datos_personales": "Perfil y datos personales",
    "mantene_actualizados_tu_nombre_correo_area_y_foto": "",
    "preferencias": "Preferencias",
    "ajusta_el_tema_el_idioma_y_como_queres_usar_el_portal": "Ajusta el tema, el idioma y como queres usar el portal.",
    "aspecto": "Aspecto",
    "claro": "Claro",
    "oscuro": "Oscuro",
    "idioma": "Idioma",
    "espanol": "Español",
    "ingles": "Ingles",
    "seguridad_de_la_cuenta": "Seguridad de la cuenta",
    "revisa_accesos_permisos_y_datos_de_inicio_de_sesion": "Revisa accesos, permisos y datos de inicio de sesion.",
    "comodidad_de_lectura": "Comodidad de lectura",
    "ajustes_pensados_para_leer_y_trabajar_con_menos_esfuer": "Ajustes pensados para leer y trabajar con menos esfuerzo.",
    "necesito_ayuda": "Necesito ayuda",
    "escribile_al_soporte_tecnico_o_reporta_un_inconvenient": "Escribile al equipo de incidencias tecnicas o reporta un inconveniente.",
    "cerrar_sesion": "Cerrar sesion",
    "cambiar_a_modo_claro": "Cambiar a modo claro",
    "cambiar_a_modo_oscuro": "Cambiar a modo oscuro",
    "home": "Home",
    "prestamos": "Prestamos",
    "solicitudes_de_servicio": "Solicitudes de servicio",
    "soporte_tecnico": "Incidencias tecnicas",
    "cuenta": "Cuenta",
    "inventario": "Inventario",
    "historial": "Historial",
    "imagenes": "Imagenes",
    "secciones": "Secciones",
    "equipos": "Equipos",
    "vacios": "Vacios",
    "usuario_solicitante": "Usuario solicitante",
    "usuario_tecnico": "Usuario tecnico",
    "usuario_administrativo": "Usuario administrativo",
    "gestion_diaria_del_area_ti": "Gestion diaria del area TI",
    "sala_de_informatica_de_una_institucion_educativa": "Sala de informatica de una institucion educativa",
    "portal_de_gestion_ti": "Portal de Gestion TI",
    "bienvenida_laura": "Bienvenida, Laura.",
    "desde_sgrsi_podes_pedir_recursos_seguir_solicitudes_re": "Desde SGRSI podes pedir recursos, seguir solicitudes y coordinar el trabajo tecnico desde un solo lugar.",
    "prestamos_activos": "Prestamos activos",
    "prestamos_tuyos_en_curso_o_pendientes": "Prestamos tuyos en curso o pendientes.",
    "solicitudes_activas": "Solicitudes activas",
    "servicios_que_siguen_en_gestion": "Servicios que siguen en gestion.",
    "tickets_abiertos": "Tickets abiertos",
    "consultas_o_reclamos_aun_activos": "Consultas o reclamos aun activos.",
    "modulos_disponibles": "Modulos disponibles",
    "accesos_principales_para_solicitar_recursos_pedir_serv": "Accesos principales para solicitar recursos, pedir servicios y contactar soporte.",
    "solicita_pcs_monitores_perifericos_y_otros_recursos_te": "Solicita PCs, monitores, perifericos y otros recursos tecnologicos.",
    "pide_preparacion_de_salones_asistencia_y_recursos_para": "Pide preparacion de salones, asistencia y recursos para una fecha especifica.",
    "registra_preguntas_incidencias_o_reclamos_al_equipo_te": "Registra preguntas, incidencias o reclamos al equipo tecnico.",
    "atajos_utiles": "Atajos utiles",
    "sugerencias_para_empezar_a_usar_los_apartados_nuevos": "Sugerencias para empezar a usar los apartados nuevos.",
    "prestamos_rapidos": "Prestamos rapidos",
    "solicita_10_pcs_monitores_o_perifericos_para_una_fecha": "Solicita 10 PCs, monitores o perifericos para una fecha concreta desde el modulo de prestamos.",
    "pide_con_anticipacion_la_preparacion_de_un_salon_apoyo": "Pide con anticipacion la preparacion de un salon, apoyo multimedia o asistencia tecnica en clase.",
    "cuenta_personal": "Cuenta personal",
    "completa_tu_descripcion_y_sube_una_foto_de_perfil_para": "Completa tu descripcion y sube una foto de perfil para identificar mejor tus solicitudes.",
    "revisa_tu_informacion_personal_actualiza_tu_foto_y_dej": "Revisa tu informacion personal, actualiza tu foto y deja claro desde que area trabajas.",
    "datos_de_tu_perfil": "Datos de tu perfil",
    "mantene_actualizados_los_datos_que_ayudan_al_equipo_a_": "Mantene actualizados los datos que ayudan al equipo a identificar tus solicitudes.",
    "nombre_completo": "Nombre completo",
    "correo": "Correo",
    "cedula": "Cedula",
    "rol": "Rol",
    "area": "Area",
    "descripcion": "Descripcion",
    "sobre_tu_trabajo": "Sobre tu trabajo",
    "foto_de_perfil": "Foto de perfil",
    "si_no_elegis_una_imagen_nueva_se_conserva_la_foto_actu": "Si no elegis una imagen nueva, se conserva la foto actual.",
    "guardar_cambios": "Guardar cambios",
    "registro": "Registro",
    "sistema": "Sistema",
    "pendiente": "Pendiente",
    "aprobado": "Aprobado",
    "denegado": "Denegado",
    "en_revision": "En revision",
    "en_proceso": "En proceso",
    "resuelto": "Resuelto",
    "total": "Total",
    "tus_prestamos_solicitados": "Tus prestamos solicitados",
    "aca_podes_seguir_cada_pedido_y_ver_si_ya_fue_aprobado_": "Aca podes seguir cada pedido y ver si ya fue aprobado, sigue pendiente o fue denegado.",
    "solicitar_un_prestamo": "Solicitar un prestamo",
    "solicitud_de_prestamo": "Solicitud de prestamo",
    "resumen_de_prestamos": "Resumen de prestamos",
    "prestamos_registrados": "Prestamos registrados",
    "listado_de_solicitudes_activas_y_reservas_ya_aprobadas": "Listado de solicitudes activas y reservas ya aprobadas.",
    "solicitud_de_soporte": "Solicitud de soporte",
    "tickets_de_soporte": "Tickets de soporte",
    "solicitar_servicio": "Solicitar servicio",
    "solicitudes_registradas": "Solicitudes registradas",
    "gestion": "Gestion",
    "fecha": "Fecha",
    "jornada": "Jornada",
    "lugar": "Lugar",
    "ubicacion": "Ubicacion",
    "solicitante": "Solicitante",
    "recursos": "Recursos",
    "prioridad": "Prioridad",
    "categoria": "Categoria",
    "asunto": "Asunto",
    "mensaje": "Mensaje",
    "entrar_al_home": "Entrar al home",
    "login": "Login",
    "register": "Register",
    "olvide_contrasena": "Olvide contraseña",
    "menu_principal_de_acceso": "Menu principal de acceso",
    "acceso_centralizado": "Acceso centralizado",
  },
  en: {
    "abrir_menu_de_cuenta": "Open account menu",
    "abrir_cuenta": "Open account",
    "configuracion": "Settings",
    "abrir_menu_de_navegacion": "Open navigation menu",
    "perfil_y_datos_personales": "Profile and personal details",
    "mantene_actualizados_tu_nombre_correo_area_y_foto": "",
    "preferencias": "Preferences",
    "ajusta_el_tema_el_idioma_y_como_queres_usar_el_portal": "Adjust the theme, language and how you use the portal.",
    "aspecto": "Appearance",
    "claro": "Light",
    "oscuro": "Dark",
    "idioma": "Language",
    "espanol": "Spanish",
    "ingles": "English",
    "seguridad_de_la_cuenta": "Account security",
    "revisa_accesos_permisos_y_datos_de_inicio_de_sesion": "Review access, permissions and sign-in details.",
    "comodidad_de_lectura": "Reading comfort",
    "ajustes_pensados_para_leer_y_trabajar_con_menos_esfuer": "Settings designed to make reading and working easier.",
    "necesito_ayuda": "I need help",
    "escribile_al_soporte_tecnico_o_reporta_un_inconvenient": "Contact technical incidents or report an issue.",
    "cerrar_sesion": "Sign out",
    "cambiar_a_modo_claro": "Switch to light mode",
    "cambiar_a_modo_oscuro": "Switch to dark mode",
    "home": "Home",
    "prestamos": "Loans",
    "solicitudes_de_servicio": "Service requests",
    "soporte_tecnico": "Technical Incidents",
    "cuenta": "Account",
    "inventario": "Inventory",
    "historial": "History",
    "imagenes": "Images",
    "secciones": "Sections",
    "equipos": "Devices",
    "vacios": "Empty rooms",
    "usuario_solicitante": "Requesting user",
    "usuario_tecnico": "Technical user",
    "usuario_administrativo": "Administrative user",
    "gestion_diaria_del_area_ti": "Daily IT area management",
    "sala_de_informatica_de_una_institucion_educativa": "Computer lab in an educational institution",
    "portal_de_gestion_ti": "IT Management Portal",
    "bienvenida_laura": "Welcome, Laura.",
    "desde_sgrsi_podes_pedir_recursos_seguir_solicitudes_re": "From SGRSI you can request resources, track requests and coordinate technical work from one place.",
    "prestamos_activos": "Active loans",
    "prestamos_tuyos_en_curso_o_pendientes": "Your active or pending loans.",
    "solicitudes_activas": "Active requests",
    "servicios_que_siguen_en_gestion": "Services still in progress.",
    "tickets_abiertos": "Open tickets",
    "consultas_o_reclamos_aun_activos": "Questions or claims still active.",
    "modulos_disponibles": "Available modules",
    "accesos_principales_para_solicitar_recursos_pedir_serv": "Main shortcuts to request resources, ask for services and contact support.",
    "solicita_pcs_monitores_perifericos_y_otros_recursos_te": "Request PCs, monitors, peripherals and other technology resources.",
    "pide_preparacion_de_salones_asistencia_y_recursos_para": "Request room preparation, assistance and resources for a specific date.",
    "registra_preguntas_incidencias_o_reclamos_al_equipo_te": "Submit questions, incidents or claims to the technical team.",
    "atajos_utiles": "Useful shortcuts",
    "sugerencias_para_empezar_a_usar_los_apartados_nuevos": "Suggestions to start using the new sections.",
    "prestamos_rapidos": "Quick loans",
    "solicita_10_pcs_monitores_o_perifericos_para_una_fecha": "Request 10 PCs, monitors or peripherals for a specific date from the loans module.",
    "pide_con_anticipacion_la_preparacion_de_un_salon_apoyo": "Request room preparation, multimedia support or in-class technical assistance in advance.",
    "cuenta_personal": "Personal account",
    "completa_tu_descripcion_y_sube_una_foto_de_perfil_para": "Complete your description and upload a profile photo to better identify your requests.",
    "revisa_tu_informacion_personal_actualiza_tu_foto_y_dej": "Review your personal information, update your photo and clarify which area you work from.",
    "datos_de_tu_perfil": "Your profile details",
    "mantene_actualizados_los_datos_que_ayudan_al_equipo_a_": "Keep updated the details that help the team identify your requests.",
    "nombre_completo": "Full name",
    "correo": "Email",
    "cedula": "ID number",
    "rol": "Role",
    "area": "Area",
    "descripcion": "Description",
    "sobre_tu_trabajo": "About your work",
    "foto_de_perfil": "Profile photo",
    "si_no_elegis_una_imagen_nueva_se_conserva_la_foto_actu": "If you do not choose a new image, the current photo is kept.",
    "guardar_cambios": "Save changes",
    "registro": "Registered",
    "sistema": "System",
    "pendiente": "Pending",
    "aprobado": "Approved",
    "denegado": "Denied",
    "en_revision": "Under review",
    "en_proceso": "In progress",
    "resuelto": "Resolved",
    "total": "Total",
    "tus_prestamos_solicitados": "Your requested loans",
    "aca_podes_seguir_cada_pedido_y_ver_si_ya_fue_aprobado_": "Here you can track each request and see whether it was approved, is still pending or was denied.",
    "solicitar_un_prestamo": "Request a loan",
    "solicitud_de_prestamo": "Loan request",
    "resumen_de_prestamos": "Loan summary",
    "prestamos_registrados": "Registered loans",
    "listado_de_solicitudes_activas_y_reservas_ya_aprobadas": "List of active requests and already approved reservations.",
    "solicitud_de_soporte": "Support request",
    "tickets_de_soporte": "Support tickets",
    "solicitar_servicio": "Request service",
    "solicitudes_registradas": "Registered requests",
    "gestion": "Management",
    "fecha": "Date",
    "jornada": "Shift",
    "lugar": "Place",
    "ubicacion": "Location",
    "solicitante": "Requester",
    "recursos": "Resources",
    "prioridad": "Priority",
    "categoria": "Category",
    "asunto": "Subject",
    "mensaje": "Message",
    "entrar_al_home": "Enter home",
    "login": "Login",
    "register": "Register",
    "olvide_contrasena": "Forgot password",
    "menu_principal_de_acceso": "Main access menu",
    "acceso_centralizado": "Centralized access",
  },
};

Object.assign(traduccionesPortal.es, {
  "derechos_reservados": "2026 SGRSI - ITI CEPT. Todos los derechos reservados.",
  "abrir_tablero": "Abrir tablero",
  "acceso_seguro_iti_cept": "Acceso Seguro ITI CEPT",
  "acceso_o_login": "Acceso o login",
  "actualizar_contrasena": "Actualizar contraseña",
  "agregar_tarea": "Agregar tarea",
  "aun_no_tenes_cuenta": "Aun no tenes cuenta?",
  "bienvenido_de_nuevo": "Bienvenido de nuevo",
  "home_hero_desc": "SGRSI es la herramienta que busca gestionar tu trabajo diario de forma eficiente y segura",
  "hero_roles_desc": "Cada perfil ve las herramientas que necesita: solicitar recursos, preparar clases, atender incidencias, revisar tareas pendientes y mantener actualizado el inventario.",
  "planilla_horario_desc": "Cada persona tiene su horario del dia y las tareas que necesita dejar visibles para el equipo.",
  "calendario": "Calendario",
  "calendario_ta_title": "Calendario T.A. | Portal de Gestion TI",
  "calendario_o_kanban": "Calendario o kanban",
  "cancelar": "Cancelar",
  "solicitudes_desc": "Carga pedidos de equipos, perifericos, salones preparados y apoyo tecnico para fechas concretas.",
  "color_en_el_calendario": "Color en el calendario",
  "register_intro": "Completa tus datos para solicitar acceso al portal SGRSI.",
  "forgot_intro": "Confirma tu cedula y correo registrado para crear una nueva contraseña.",
  "confirmar_contrasena": "Confirmar contraseña",
  "contacto": "Contacto",
  "soporte_publico_placeholder": "Contanos que paso, en que pantalla estabas y que esperabas que ocurriera.",
  "soporte_privado_placeholder": "Contanos que paso, donde ocurrio y que necesitas que revise el equipo tecnico.",
  "contexto_de_la_pagina": "Contexto de la pagina",
  "contrasena": "Contraseña",
  "control_institucional": "Control institucional",
  "correo_electronico": "Correo electronico",
  "correo_o_cedula": "Correo o cedula",
  "correo_o_telefono_de_contacto": "Correo o telefono de contacto",
  "crea_una_cuenta": "Crea una cuenta",
  "crear_cuenta": "Crear cuenta",
  "cuenta_title": "Cuenta | Portal de Gestion TI",
  "datos_protegidos": "Datos protegidos",
  "describe_problema_soporte": "Describe el problema, desde cuando ocurre y que probaste hasta ahora.",
  "describe_perfil": "Describe tu perfil institucional...",
  "descripcion_bio": "DESCRIPCION",
  "detalle": "Detalle",
  "detalle_equipo_title": "Detalle de equipo | Inventario",
  "detalle_tarea": "Detalle de la tarea",
  "detalle_seccion_title": "Detalle de seccion | Inventario",
  "dificultad": "Dificultad",
  "donde": "Dónde",
  "ej_cedula": "Ej. 12345678",
  "ej_proyector": "Ej. El proyector no muestra imagen",
  "ej_gestion_tecnologica": "Ej. Gestion tecnologica",
  "ej_servicio": "Ej. Instalar software, dejar el salon pronto o preparar material didactico.",
  "ej_no_login": "Ej. No puedo iniciar sesion",
  "ej_prestamo": "Ej. Prueba de programacion en el Teorico 3 con el grupo de la mañana.",
  "login_security_note": "El acceso es solo para personal autorizado. Las acciones quedan registradas para cuidar la informacion institucional.",
  "public_hero_desc": "El portal para pedir recursos, coordinar servicios, atender soporte, mantener inventario y organizar el trabajo tecnico-administrativo del ITI.",
  "elegir_jornada": "Elegir jornada",
  "elegir_tipo_de_problema": "Elegir tipo de problema",
  "eliminar_tarea": "Eliminar tarea",
  "empieza": "Empieza",
  "enlaces_institucionales": "Enlaces institucionales",
  "entrar_al_portal": "Entrar al portal",
  "enviar_consulta": "Enviar consulta",
  "enviar_problema": "Enviar problema",
  "enviar_solicitud": "Enviar solicitud",
  "estado": "Estado",
  "estados_vacios_title": "Estados vacios | Inventario",
  "estados_vacios_mensajes_title": "Estados vacios | Mensajes para pantallas sin datos",
  "fecha_de_carga": "Fecha de carga",
  "gestion_integrada": "Gestion integrada",
  "gestion_clara": "Gestion tecnologica clara y centralizada.",
  "historial_cambios_title": "Historial de cambios | Inventario",
  "home_title": "Home | Portal de Gestion TI",
  "imagenes_secciones_title": "Imagenes de secciones | Inventario",
  "indicadores_de_seguridad": "Indicadores de seguridad",
  "login_intro": "Ingresa con tu correo o cedula para continuar trabajando en el portal.",
  "inicia_sesion": "Inicia sesion",
  "iniciar_sesion": "Iniciar sesion",
  "inicio_sgrsi": "Inicio SGRSI",
  "inicio_title": "Inicio | Portal de Gestion TI",
  "inventario_title": "Inventario | Portal de Gestion TI",
  "kanban": "Kanban",
  "kanban_ta": "Kanban T.A.",
  "cedula_placeholder_forgot": "La cedula de tu cuenta",
  "laboratorio_institucional": "Laboratorio informatico institucional",
  "login_title": "Login | SGRSI",
  "calendario_marcados_desc": "Los dias marcados muestran cuando empieza y termina cada tarea pendiente.",
  "lugar_de_entrega": "Lugar de entrega",
  "mantener_sesion": "Mantener sesion iniciada",
  "manana": "Mañana",
  "mes_anterior": "Mes anterior",
  "mes_siguiente": "Mes siguiente",
  "mostrar_contrasena": "Mostrar contraseña",
  "no_tenes_cuenta": "No tenes cuenta?",
  "noche": "Noche",
  "nombre_tarea": "Nombre de la tarea",
  "nombre_y_apellido": "Nombre y apellido",
  "nueva_contrasena": "Nueva contraseña",
  "oficina_soporte_alt": "Oficina institucional de soporte tecnologico",
  "olvidaste_contrasena": "Olvidaste tu contraseña?",
  "otro": "Otro",
  "para_que_se_necesita": "Para que se necesita",
  "pedir_ayuda_tecnica": "Pedir ayuda tecnica",
  "pedir_servicio": "Pedir un servicio",
  "planilla_ta_title": "Planilla de T.A. | Portal de Gestion TI",
  "plantel_tecnico_administrativo": "Plantel tecnico-administrativo",
  "portal_iti": "Portal ITI",
  "portal_iti_cept": "Portal ITI CEPT",
  "prestamos_o_solicitudes": "Prestamos o solicitudes",
  "prestamos_title": "Prestamos | Portal de Gestion TI",
  "primero_categoria": "Primero elegi una categoria para ver los recursos disponibles.",
  "que_esta_pasando": "Que esta pasando",
  "que_hay_que_hacer": "Que hay que hacer",
  "que_hay_que_preparar": "Que hay que preparar",
  "que_podes_resolver": "Que podes resolver desde aca",
  "recuperar_acceso": "Recuperar acceso",
  "recuperar_contrasena_title": "Recuperar contraseña | SGRSI",
  "recursos_y_cantidades": "Recursos y cantidades",
  "register_title": "Register | SGRSI",
  "registrarse": "Registrarse",
  "registrate": "Registrate",
  "registro_de_usuario": "Registro de usuario",
  "reportar_problema": "Reportar un problema",
  "respaldo_consultado": "Respaldo consultado:",
  "responsable": "Responsable",
  "inventario_public_desc": "Revisa inventario y seguimiento administrativo sin cambiar de herramienta.",
  "salon": "Salón",
  "secciones_title": "Secciones | Inventario",
  "support_public_desc": "Si tenes dificultades para acceder, registrar una solicitud o usar algun modulo, deja el reporte con el mayor contexto posible para que el equipo tecnico pueda ayudarte.",
  "sin_respaldos_cargados": "Sin respaldos cargados",
  "solicita_recursos_desc": "Solicita los recursos que necesitas y espera la respuesta de los técnicos.",
  "solicita_servicio_desc": "Solicita un servicio y espera la respuesta de los técnicos.",
  "solicitudes_servicio_title": "Solicitudes de servicio | Portal de Gestion TI",
  "solicitudes_y_prestamos": "Solicitudes y prestamos",
  "soporte": "Soporte",
  "soporte_publico": "Soporte publico",
  "soporte_tecnico_title": "Incidencias tecnicas | Portal de Gestion TI",
  "sumate_portal": "Sumate al portal del ITI.",
  "tablero_de_tareas": "Tablero de tareas",
  "tarde": "Tarde",
  "tareas_agrupadas_desc": "Este tablero muestra las tareas que tenes pendientes,en curso, en revision o completado",
  "termina": "Termina",
  "tipo_de_problema": "Tipo de problema",
  "tipo_de_servicio": "Tipo de servicio",
  "todos_equipos_title": "Todos los equipos | Inventario",
  "trabajo_mas_ordenado": "Trabajo mas ordenado",
  "trabajo_tecnico": "Trabajo tecnico",
  "resumen_trabajo_ta": "Un resumen rapido del trabajo tecnico-administrativo en curso.",
  "planilla_intro_desc": "Usa la planilla diaria, el calendario T.A. y el kanban para ordenar prioridades del equipo.",
  "ver_datos": "Ver datos",
  "vista_calendario_tecnico": "Vista del calendario tecnico",
  "volver_login": "Volver al inicio de sesion",
  "ya_tenes_cuenta": "Ya tenes cuenta?",
  "usuario_campus_placeholder": "usuario@campus.local"
});

Object.assign(traduccionesPortal.es, {
  "sgrsi": "SGRSI",
  "iti_cept": "ITI CEPT",
  "gestion_ti_institucional": "Gestion TI Institucional",
  "footer_derechos_fragmento": "Todos los derechos reservados.",
  "acciones_registradas": "Las acciones quedan registradas para cuidar la informacion institucional.",
  "register_security_desc": "SGRSI ayuda a ordenar pedidos, soporte, inventario y tareas del equipo tecnico-administrativo.",
  "calendario_ta": "Calendario T.A.",
  "planilla_ta": "Planilla de T.A.",
  "fecha_placeholder": "dd/mm/aaaa",
  "hora_placeholder": "hh:mm",
  "todas_las_secciones": "Todas las secciones",
  "ver_respaldo": "Ver respaldo",
  "seccion": "Seccion",
  "detalle_opcional_equipo": "Detalle opcional del estado o ubicacion dentro del salon.",
  "ej_laboratorio": "Ej. Laboratorio 6",
  "ej_monitor": "Ej. Monitor biblioteca 1",
  "buscar_equipo": "Buscar equipo...",
  "buscar_historial": "Buscar en historial...",
  "buscar_seccion": "Buscar seccion...",
  "ocultar_contrasena": "Ocultar contraseña",
  "ver_todo": "Ver todo",
  "ver_detalle": "Ver detalle",
  "todo_al_dia": "Todo al dia",
  "nuevo_acceso_creado": "Nuevo acceso creado",
  "prestamos_de_equipos": "Prestamos de equipos",
  "prestamos_de_equipos_desc": "Pedi PCs, perifericos o monitores con la fecha, la jornada y el lugar de uso.",
  "elegir_categoria": "Elegir categoria",
  "elegir_lugar": "Elegir lugar",
  "prestamos_empty": "Todavia no hay prestamos para mostrar con este perfil.",
  "elegir_tipo_servicio": "Elegir tipo de servicio",
  "elegir_salon": "Elegir salón",
  "solicitudes_empty": "Todavia no hay solicitudes de servicio para mostrar con este perfil.",
  "soporte_desc": "Envia consultas o incidencias para que el equipo tecnico pueda revisarlas y responder.",
  "soporte_panel_desc": "Envia consultas y segui aca mismo si estan en revision, resueltas o denegadas.",
  "elige_lugar": "Elige un lugar",
  "soporte_empty": "Todavia no hay tickets de soporte para mostrar con este perfil.",
  "sin_area_definida": "Sin area definida",
  "todavia_no_tareas": "Todavia no hay tareas cargadas para esta jornada.",
  "todavia_no_equipos": "Todavia no hay equipos cargados",
  "todavia_no_cambios": "Todavia no hay cambios registrados",
  "todavia_no_secciones": "Todavia no hay secciones registradas",
  "todavia_no_integrantes": "Todavia no hay integrantes tecnico-administrativos para mostrar.",
  "elegir_tipo": "Elegir tipo",
  "equipos_count": "equipos",
  "equipo": "Equipo",
  "tipo": "Tipo",
  "actualizacion": "Actualizacion",
  "acciones": "Acciones",
  "dar_de_baja_equipo": "Dar de baja equipo",
  "dar_de_baja_seccion": "Dar de baja seccion",
  "pc_categoria": "PCs",
  "perifericos_categoria": "Perifericos",
  "monitores_categoria": "Monitores",
  "mouse_recurso": "Mouse",
  "teclados_recurso": "Teclados",
  "parlantes_recurso": "Parlantes",
  "torres_recurso": "Torres",
  "all_in_ones_recurso": "All in ones"
});

Object.assign(traduccionesPortal.es, {
  "navegacion_principal": "Navegacion principal",
  "elegir_rol": "Elegir rol"
});

Object.assign(traduccionesPortal.en, {
  "derechos_reservados": "2026 SGRSI - ITI CEPT. All rights reserved.",
  "abrir_tablero": "Open dashboard",
  "acceso_seguro_iti_cept": "Secure Access ITI CEPT",
  "acceso_o_login": "Access or login",
  "actualizar_contrasena": "Update password",
  "agregar_tarea": "Add task",
  "aun_no_tenes_cuenta": "Don't have an account yet?",
  "bienvenido_de_nuevo": "Welcome back",
  "home_hero_desc": "SGRSI is the tool designed to help you manage your daily work efficiently and securely.",
  "hero_roles_desc": "Each profile sees the tools it needs: request resources, prepare classes, handle incidents, review pending tasks and keep inventory updated.",
  "planilla_horario_desc": "Each person has their daily schedule and the tasks they need to keep visible for the team.",
  "calendario": "Calendar",
  "calendario_ta_title": "A.T. Calendar | IT Management Portal",
  "calendario_o_kanban": "Calendar or kanban",
  "cancelar": "Cancel",
  "solicitudes_desc": "Load requests for equipment, peripherals, prepared rooms and technical incidents for specific dates.",
  "color_en_el_calendario": "Calendar color",
  "register_intro": "Complete your information to request access to the SGRSI portal.",
  "forgot_intro": "Confirm your ID number and registered email to create a new password.",
  "confirmar_contrasena": "Confirm password",
  "contacto": "Contact",
  "soporte_publico_placeholder": "Tell us what happened, which screen you were on and what you expected to happen.",
  "soporte_privado_placeholder": "Tell us what happened, where it occurred and what you need the technical team to review.",
  "contexto_de_la_pagina": "Page context",
  "contrasena": "Password",
  "control_institucional": "Institutional control",
  "correo_electronico": "Email",
  "correo_o_cedula": "Email or ID number",
  "correo_o_telefono_de_contacto": "Contact email or phone",
  "crea_una_cuenta": "Create an account",
  "crear_cuenta": "Create account",
  "cuenta_title": "Account | IT Management Portal",
  "datos_protegidos": "Protected data",
  "describe_problema_soporte": "Describe the problem, when it started and what you have already tried.",
  "describe_perfil": "Describe your institutional profile...",
  "descripcion_bio": "DESCRIPCION",
  "detalle": "Detail",
  "detalle_equipo_title": "Equipment detail | Inventory",
  "detalle_tarea": "Task detail",
  "detalle_seccion_title": "Section detail | Inventory",
  "dificultad": "Difficulty",
  "donde": "Where",
  "ej_cedula": "Ex. 12345678",
  "ej_proyector": "Ex. The projector is not showing an image",
  "ej_gestion_tecnologica": "Ex. Technology management",
  "ej_servicio": "Ex. Install software, prepare the room or prepare teaching material.",
  "ej_no_login": "Ex. I cannot sign in",
  "ej_prestamo": "Ex. Programming test in Theory Room 3 with the morning group.",
  "login_security_note": "Access is only for authorized personnel. Actions are recorded to protect institutional information.",
  "public_hero_desc": "The portal for requesting resources, coordinating services, handling support, maintaining inventory and organizing technical-administrative work at ITI.",
  "elegir_jornada": "Choose shift",
  "elegir_tipo_de_problema": "Choose problem type",
  "eliminar_tarea": "Delete task",
  "empieza": "Starts",
  "enlaces_institucionales": "Institutional links",
  "entrar_al_portal": "Enter portal",
  "enviar_consulta": "Send inquiry",
  "enviar_problema": "Send problem",
  "enviar_solicitud": "Send request",
  "estado": "Status",
  "estados_vacios_title": "Empty states | Inventory",
  "estados_vacios_mensajes_title": "Empty states | Messages for screens with no data",
  "fecha_de_carga": "Load date",
  "gestion_integrada": "Integrated management",
  "gestion_clara": "Clear and centralized technology management.",
  "historial_cambios_title": "Change history | Inventory",
  "home_title": "Home | IT Management Portal",
  "imagenes_secciones_title": "Section images | Inventory",
  "indicadores_de_seguridad": "Security indicators",
  "login_intro": "Sign in with your email or ID number to continue working in the portal.",
  "inicia_sesion": "Sign in",
  "iniciar_sesion": "Sign in",
  "inicio_sgrsi": "SGRSI Home",
  "inicio_title": "Home | IT Management Portal",
  "inventario_title": "Inventory | IT Management Portal",
  "kanban": "Kanban",
  "kanban_ta": "A.T. Kanban",
  "cedula_placeholder_forgot": "Your account ID number",
  "laboratorio_institucional": "Institutional computer lab",
  "login_title": "Login | SGRSI",
  "calendario_marcados_desc": "Marked days show when each pending task starts and ends.",
  "lugar_de_entrega": "Delivery location",
  "mantener_sesion": "Keep me signed in",
  "manana": "Morning",
  "mes_anterior": "Previous month",
  "mes_siguiente": "Next month",
  "mostrar_contrasena": "Show password",
  "no_tenes_cuenta": "Don't have an account?",
  "noche": "Night",
  "nombre_tarea": "Task name",
  "nombre_y_apellido": "Full name",
  "nueva_contrasena": "New password",
  "oficina_soporte_alt": "Institutional technology support office",
  "olvidaste_contrasena": "Forgot your password?",
  "otro": "Other",
  "para_que_se_necesita": "What it is needed for",
  "pedir_ayuda_tecnica": "Request technical help",
  "pedir_servicio": "Request a service",
  "planilla_ta_title": "A.T. Sheet | IT Management Portal",
  "plantel_tecnico_administrativo": "Technical-administrative staff",
  "portal_iti": "ITI Portal",
  "portal_iti_cept": "ITI CEPT Portal",
  "prestamos_o_solicitudes": "Loans or requests",
  "prestamos_title": "Loans | IT Management Portal",
  "primero_categoria": "Choose a category first to see available resources.",
  "que_esta_pasando": "What is happening",
  "que_hay_que_hacer": "What needs to be done",
  "que_hay_que_preparar": "What needs to be prepared",
  "que_podes_resolver": "What you can handle here",
  "recuperar_acceso": "Recover access",
  "recuperar_contrasena_title": "Recover password | SGRSI",
  "recursos_y_cantidades": "Resources and quantities",
  "register_title": "Register | SGRSI",
  "registrarse": "Register",
  "registrate": "Register",
  "registro_de_usuario": "User registration",
  "reportar_problema": "Report a problem",
  "respaldo_consultado": "Backup viewed:",
  "responsable": "Responsible",
  "inventario_public_desc": "Review inventory and administrative tracking without switching tools.",
  "salon": "Room",
  "secciones_title": "Sections | Inventory",
  "support_public_desc": "If you have trouble accessing, registering a request or using any module, leave the report with as much context as possible so the technical team can help you.",
  "sin_respaldos_cargados": "No backups loaded",
  "solicita_recursos_desc": "Request the resources you need and wait for the technicians' response.",
  "solicita_servicio_desc": "Request a service and wait for the technicians' response.",
  "solicitudes_servicio_title": "Service requests | IT Management Portal",
  "solicitudes_y_prestamos": "Requests and loans",
  "soporte": "Support",
  "soporte_publico": "Public support",
  "soporte_tecnico_title": "Technical Incidents | IT Management Portal",
  "sumate_portal": "Join the ITI portal.",
  "tablero_de_tareas": "Task board",
  "tarde": "Afternoon",
  "tareas_agrupadas_desc": "Este tablero muestra las tareas que tenes pendientes,en curso, en revision o completado",
  "termina": "Ends",
  "tipo_de_problema": "Problem type",
  "tipo_de_servicio": "Service type",
  "todos_equipos_title": "All equipment | Inventory",
  "trabajo_mas_ordenado": "More organized work",
  "trabajo_tecnico": "Technical work",
  "resumen_trabajo_ta": "A quick summary of current technical-administrative work.",
  "planilla_intro_desc": "Use the daily sheet, A.T. calendar and kanban to organize team priorities.",
  "ver_datos": "View data",
  "vista_calendario_tecnico": "Technical calendar view",
  "volver_login": "Back to sign in",
  "ya_tenes_cuenta": "Already have an account?",
  "usuario_campus_placeholder": "user@campus.local"
});

Object.assign(traduccionesPortal.en, {
  "sgrsi": "SGRSI",
  "iti_cept": "ITI CEPT",
  "gestion_ti_institucional": "Institutional IT Management",
  "footer_derechos_fragmento": "All rights reserved.",
  "acciones_registradas": "Actions are recorded to protect institutional information.",
  "register_security_desc": "SGRSI helps organize requests, support, inventory and technical-administrative team tasks.",
  "calendario_ta": "A.T. Calendar",
  "planilla_ta": "A.T. Sheet",
  "fecha_placeholder": "dd/mm/yyyy",
  "hora_placeholder": "hh:mm",
  "todas_las_secciones": "All sections",
  "ver_respaldo": "View backup",
  "seccion": "Section",
  "detalle_opcional_equipo": "Optional detail about the status or location inside the room.",
  "ej_laboratorio": "Ex. Lab 6",
  "ej_monitor": "Ex. Library monitor 1",
  "buscar_equipo": "Search equipment...",
  "buscar_historial": "Search history...",
  "buscar_seccion": "Search section...",
  "ocultar_contrasena": "Hide password",
  "ver_todo": "View all",
  "ver_detalle": "View details",
  "todo_al_dia": "All caught up",
  "nuevo_acceso_creado": "New access created",
  "prestamos_de_equipos": "Equipment loans",
  "prestamos_de_equipos_desc": "Request PCs, peripherals or monitors with the date, shift and place of use.",
  "elegir_categoria": "Choose category",
  "elegir_lugar": "Choose location",
  "prestamos_empty": "There are no loans to show for this profile yet.",
  "elegir_tipo_servicio": "Choose service type",
  "elegir_salon": "Choose room",
  "solicitudes_empty": "There are no service requests to show for this profile yet.",
  "soporte_desc": "Send inquiries or incidents so the technical team can review and respond.",
  "soporte_panel_desc": "Send inquiries and track here whether they are under review, resolved or denied.",
  "elige_lugar": "Choose a location",
  "soporte_empty": "There are no support tickets to show for this profile yet.",
  "sin_area_definida": "No area defined",
  "todavia_no_tareas": "There are no tasks loaded for this shift yet.",
  "todavia_no_equipos": "There is no equipment loaded yet",
  "todavia_no_cambios": "There are no registered changes yet",
  "todavia_no_secciones": "There are no registered sections yet",
  "todavia_no_integrantes": "There are no technical-administrative members to show yet.",
  "elegir_tipo": "Choose type",
  "equipos_count": "equipment",
  "equipo": "Equipment",
  "tipo": "Type",
  "actualizacion": "Updated",
  "acciones": "Actions",
  "dar_de_baja_equipo": "Deactivate equipment",
  "dar_de_baja_seccion": "Deactivate section",
  "pc_categoria": "PCs",
  "perifericos_categoria": "Peripherals",
  "monitores_categoria": "Monitors",
  "mouse_recurso": "Mouse",
  "teclados_recurso": "Keyboards",
  "parlantes_recurso": "Speakers",
  "torres_recurso": "Towers",
  "all_in_ones_recurso": "All-in-ones"
});

Object.assign(traduccionesPortal.en, {
  "navegacion_principal": "Main navigation",
  "elegir_rol": "Choose role"
});

window.traducciones = traduccionesPortal;
